Repository shahdivyank/beatdrop, pull requests merged in 2023-01, with the labels that each got.

#14 specific colors added to tailwind.config
  pages/index.js
  tailwind.config.js
Labels: Repository

#16 Add Bootstrap CSS File
  pages/_app.js
Labels: Ready for Review

#18 adequate navbar
  components/Navigation.jsx
  package-lock.json
  package.json
  pages/index.js
  public/beatdrop-white.png
Labels: Ready for Review

#20 Zorten/welcome
  components/Navigation.jsx
  components/Welcome.jsx
  pages/_document.js
  pages/index.js
  public/beatdrop-logo-black-headphones.png
  public/beatdrop-logo-white-headphones.png
  public/beatdrop-logo-white-text.png
  public/beatdrop-white.png
  public/favicon.ico
  static/favicon.ico
Labels: Landing

#26 Added next/Image to Navigation
  components/Navigation.jsx
Labels: Navigation

#24 Google Deployment
  .dockerignore
  Dockerfile
  app.json
Labels: Ready for Review

#27 next images on landing
  components/Welcome.jsx
Labels: Landing
