Repository shahdivyank/beatdrop, pull requests merged in 2023-04, with the labels that each got.

#337 Removed Unused Images
  components/AboutSVGIntroduction.jsx
  components/ProfileInformation.jsx
  components/Welcome.jsx
  public/Pink_Friday_album_cover.jpg
  public/beatdrop-logo-black-headphones.png
  public/beatdrop-logo-white-headphones-introduction.png
  public/beatdrop-logo-white-headphones-welcome.png
  public/beatdrop-logo-white-headphones.png
  public/beatdrop-logo_black.png
  public/beatdrop.png
  public/ditto.jpg
  public/map_pink.png
Labels: Repository, Ready for Review

#335 Convert to next/Image
  components/ProfileImage.jsx
  components/Profiledrop.jsx
  components/Song.jsx
  components/Upload.jsx
  components/View.jsx
  components/WhoIsBeatdrop.jsx
  next.config.js
Labels: Repository, Navigation, Landing, Dashboard, Ready for Review, Profile, About, Map

#338 Fix Border Issue
  components/View.jsx
Labels: Dashboard, Ready for Review

#336 SVG Folder
  components/SVGs/AboutSVG.jsx
  components/SVGs/AboutSVGIntroduction.jsx
  components/SVGs/IndexSVG.jsx
  cypress/component/IndexSVG.cy.jsx
  pages/about.js
  pages/index.js
Labels: Repository, Ready for Review

#340 User Context
  components/Navigation.jsx
  components/Overlay.jsx
  components/Upload.jsx
  components/Welcome.jsx
  pages/_app.js
  pages/map.js
  pages/profile.js
Labels: Navigation, Dashboard, Profile, Backend

#341 Optimize Bootstrap Imports
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  components/Upload.jsx
  pages/about.js
  pages/profile.js
Labels: Repository

#349 profile drop hashtags widthsfit text
  components/Profiledrop.jsx
Labels: Ready for Review, Profile, Bugfix

#354 Code Cleanup
  components/Listing.jsx
  components/Navigation.jsx
  components/ProfileImage.jsx
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  components/SVGs/AboutSVG.jsx
  components/SVGs/AboutSVGIntroduction.jsx
  components/SVGs/IndexSVG.jsx
  components/Song.jsx
  components/Upload.jsx
  components/View.jsx
  components/WhatIsBeatdrop.jsx
  components/WhoIsBeatdrop.jsx
  pages/index.js
  pages/profile.js
Labels: Repository, Navigation, Landing, Dashboard, Ready for Review, Profile, About, Map

#359 Fix eventKey Bug
  components/Navigation.jsx
  components/Profiledrop.jsx
Labels: Bugfix

#363 Made token a global variable by adding it to useContext
  components/Welcome.jsx
  pages/_app.js
  pages/map.js
Labels: Ready for Review, Backend

#364 Fix `eventKey` Bug
  components/Profiledrop.jsx
Labels: Bugfix

#365 replaced in console logs in exchange for eastereggs
  components/Gmap.jsx
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  components/Upload.jsx
  components/View.jsx
  pages/_app.js
  pages/api/getPrivateDrops.js
  pages/api/getProfileDrops.js
Labels: Backend
