Repository shahdivyank/beatdrop, pull requests merged in 2023-02, with the labels that each got.

#29 Song Components files
  components/Song.jsx
  loop.txt
  pages/index.js
  public/ditto.jpg
Labels: Dashboard, Ready for Review

#28 Added Listing Component
  components/Listing.jsx
  pages/index.js
  tailwind.config.js
Labels: Ready for Review

#25 Added Outfit Font
  components/List.jsx
  package-lock.json
  package.json
  pages/_app.js
Labels: Repository, Ready for Review

#35 Setup Dashboard
  components/Listing.jsx
  components/Overlay.jsx
  package-lock.json
  pages/index.js
  pages/map.js
  pages/profile.js
Labels: Dashboard, Ready for Review

#31 Fix Deployment
  package.json
Labels: Ready for Review

#38 Remove Prod Flag on Deployment
  Dockerfile
Labels: Ready for Review

#44 Add Cloudbuild
  cloudbuild.yaml
Labels: Repository, Ready for Review

#45 Mgolwalla/layout
  components/Layout.jsx
  pages/_app.js
Labels: Navigation, Ready for Review

#19 Added Login UI
  components/Login.jsx
Labels: Landing

#15 Create View Component
  components/View.jsx
Labels: Dashboard, Ready for Review

#50 switched order of profile and map in navegation
  components/Navigation.jsx
Labels: Navigation, Ready for Review

#49 Lb rodrigo/404
  pages/404.js
Labels: Repository, Ready for Review

#54 Bobbyyy57/listwithsongs
  components/Listing.jsx
  components/Song.jsx
  pages/map.js
  tailwind.config.js
Labels: Dashboard, Ready for Review

#53 About Page
  components/AboutNav.jsx
  components/Developer.jsx
  components/Developers.jsx
  components/Introduction.jsx
  components/Navigation.jsx
  loop.txt
  pages/_app.js
  pages/about.js
  pages/index.js
  public/jisoo.png
  tailwind.config.js
Labels: Ready for Review

#63 Add About SVG
  pages/about.js
Labels: Ready for Review, About

#61 Add 404 SVG Path
  components/Navigation.jsx
  pages/404.js
Labels: Repository, Ready for Review

#60 profile drop
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  pages/profile.js
  public/Pink_Friday_album_cover.jpg
Labels: Ready for Review, Profile

#69 Fixed Google Cloud Build error
  components/Song.jsx
Labels: Bugfix

#70 Remove Song Title
  components/Listing.jsx
Labels: Ready for Review, Bugfix

#74 tabs fixed
  pages/404.js
  pages/about.js
  pages/index.js
  pages/map.js
  pages/profile.js
Labels: Repository, Ready for Review

#75 Mgolwalla/landing
  components/Navigation.jsx
  components/Welcome.jsx
  package-lock.json
  pages/index.js
Labels: Landing, Ready for Review

#76 map pngs added
  public/map_pink.png
  public/map_yellow.png
Labels: Landing, Ready for Review

#77 Off White Background
  pages/404.js
  pages/about.js
  pages/profile.js
Labels: Repository, Dashboard, Ready for Review, About

#78 404 page with svg
  pages/404.js
Labels: Ready for Review

#79 Setup Firebase Auth
  .eslintignore
  .gitignore
  .prettierignore
  components/Navigation.jsx
  components/Welcome.jsx
  firebase.js
  package-lock.json
  package.json
Labels: Repository, Ready for Review

#80 Add Firebase Env Vars
  cloudbuild.yaml
Labels: Ready for Review, Bugfix

#81 Add Package Script
  package.json
Labels: Ready for Review, Bugfix

#82 Fixed Spacing for Introduction in About Page
  components/Introduction.jsx
Labels: About

#84 uppercase titles
  pages/404.js
  pages/about.js
  pages/index.js
  pages/map.js
  pages/profile.js
Labels: Ready for Review

#86 Profile Page
  components/ProfileImage.jsx
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  components/Welcome.jsx
  pages/profile.js
Labels: Ready for Review, Profile

#90 font unbolded
  pages/404.js
Labels: Ready for Review

#89 Mgolwalla/aboutimproved
  components/AboutNav.jsx
  components/AboutSVG.jsx
  components/AboutSVGIntroduction.jsx
  components/Introduction.jsx
  components/WhatIsBeatdrop.jsx
  components/WhoIsBeatdrop.jsx
  components/holder.jsx
  pages/about.js
  public/Bobby.png
  public/Divyank.png
  public/MariamG.png
  public/Rodrigo.png
  public/William.png
  public/Zergio.png
  public/beatdrop-logo-white.png
  public/beatdrop.png
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
Labels: About

#91 Added Hover Button and Fixed Posted Casing
  components/Listing.jsx
  components/Song.jsx
  tailwind.config.js
Labels: Dashboard, Ready for Review, Bugfix

#92 Fix Opacity Issue
  components/AboutSVG.jsx
Labels: Ready for Review, Bugfix

#94 new about page
  components/AboutSVG.jsx
  components/WhatIsBeatdrop.jsx
  pages/about.js
  pages/index.js
Labels: Ready for Review, About

#96 beatdrop smaller for bobby
  components/AboutSVG.jsx
Labels: About

#97 Cypress Testing
  .eslintrc.json
  .github/workflows/main.yaml
  .husky/pre-commit
  cypress.config.js
  cypress/e2e/welcome.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Ready for Review, Testing

#107 Add Cypress to Tech Stack
  components/WhatIsBeatdrop.jsx
Labels: Ready for Review, About

#110 Replaced Zergio
  public/Zergio.png
Labels: Ready for Review, About

#109 Fix About SVG Spacing
  .github/workflows/main.yaml
  components/AboutSVG.jsx
Labels: Ready for Review, About

#111 Fix Hover
  components/Listing.jsx
Labels: Dashboard, Ready for Review

#117 Small Clean Ups on About
  components/AboutSVGIntroduction.jsx
  components/WhatIsBeatdrop.jsx
  components/WhoIsBeatdrop.jsx
  package-lock.json
  package.json
  pages/about.js
Labels: Ready for Review, About

#120 Small Details: NavBar + Profile Name
  components/Navigation.jsx
  components/ProfileInformation.jsx
Labels: Navigation, Ready for Review, Profile

#123 changed size of circle for error pages + fixed 505 font weight
  pages/404.js
  pages/500.js
Labels: Repository, Ready for Review

#125 Lb rodrigo/profile drops
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  tailwind.config.js
Labels: Ready for Review, Profile

#128 About Test
  cypress/e2e/about.cy.js
Labels: Ready for Review, Testing

#129 Finalize GMap
  components/Gmap.jsx
  components/Overlay.jsx
  package-lock.json
  package.json
  pages/map.js
Labels: Dashboard, Ready for Review

#132 Connect View and Listing
  components/Developer.jsx
  components/Developers.jsx
  components/Listing.jsx
  components/Login.jsx
  components/View.jsx
Labels: Dashboard, Ready for Review

#136 Setup Upload Button Functionality
  components/Listing.jsx
  components/Upload.jsx
  public/jisoo.png
Labels: Dashboard

#143 sign in test
  cypress/e2e/signin_landing.cy.js
  package-lock.json
Labels: Testing

#141 Disable street view in gmap
  components/Gmap.jsx
Labels: Dashboard

#144 Deleted Friends from Profile and Map pages
  components/Listing.jsx
  components/ProfileInformation.jsx
Labels: Profile

#145 Pulled Username from Firebase
  components/View.jsx
Labels: Dashboard, Ready for Review

#146 scrollbar implemented
  components/Profiledrops.jsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Profile

#147 spacing in profile page fixed
  pages/profile.js
Labels: Profile

#163 Add Build Step
  .github/workflows/main.yaml
Labels: Repository, Ready for Review

#164 individual bd cleaned up
  components/Listing.jsx
  components/View.jsx
  cypress/e2e/whatisbd.js
Labels: Ready for Review

#161 Optimize Imports
  components/Profiledrops.jsx
  components/View.jsx
  components/WhatIsBeatdrop.jsx
Labels: Ready for Review, Bugfix

#165 Add Separate Errors For Listing
  components/Listing.jsx
  components/Song.jsx
Labels: Dashboard, Ready for Review

#168 what is beatdrop test
  cypress/e2e/whatisbd.js
Labels: Ready for Review, Testing

#166 Dropdown on Beatdrops
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  cypress/e2e/description_tech.cy.js
  pages/profile.js
Labels: Ready for Review, Profile

#169 Mgolwalla/whatisbdtest
  cypress/e2e/whatisbd.cy.js
Labels: Ready for Review, Bugfix

#171 Pencil Icon Added to Profile Page
  components/ProfileInformation.jsx
Labels: Ready for Review, Profile
