Repository shahdivyank/beatdrop, pull requests merged in 2023-03, with the labels that each got.

#172 beatdrop width fixed
  components/View.jsx
Labels: Ready for Review, Bugfix

#173 Spotify API Integration
  components/Song.jsx
  package-lock.json
  package.json
  pages/api/getToken.js
Labels: Do Not Merge, Backend, Spotify

#181 Mgolwalla/uploadpullname
  components/Listing.jsx
  components/Upload.jsx
  components/View.jsx
Labels: Ready for Review, Backend

#178 view component updated
  components/Listing.jsx
  components/View.jsx
Labels: Ready for Review, Map

#180 Pulled Profile Information from Firestore DB
  pages/api/getUserInfo.js
  pages/profile.js
Labels: Ready for Review, Profile, Backend

#176 Added scroll bar and stylized
  components/Listing.jsx
Labels: Ready for Review, Bugfix, Map

#175 added gmap Custom Marker example
  components/Gmap.jsx
Labels: Dashboard

#182 who is bd cypress test
  cypress/e2e/whoisbd.cy.js
Labels: Testing

#191 Fixed bug when trying to access About page when not logged in.
  components/Navigation.jsx
  pages/profile.js
Labels: Ready for Review, Bugfix, About

#189 double click creates marker
  components/Gmap.jsx
Labels: Map

#185 signout bugfix
  components/Welcome.jsx
Labels: Bugfix

#193 Click on arrow to close View component
  components/Listing.jsx
Labels: Ready for Review, Map

#194 Fixed DOM warnings
  pages/404.js
Labels: Ready for Review, Bugfix

#195 Fix View Component UI
  components/Song.jsx
  components/View.jsx
Labels: Dashboard, Ready for Review

#199 Public Songs
  components/Listing.jsx
  components/Song.jsx
  components/View.jsx
  pages/api/getPublicDrops.js
Labels: Dashboard, Backend

#203 Added spacing hehehe
  components/View.jsx
Labels: Map

#202 fixed dom warnings
  components/AboutSVG.jsx
  components/AboutSVGIntroduction.jsx
  components/holder.jsx
  pages/500.js
  pages/index.js
Labels: Ready for Review, Bugfix

#204 Cleaned up Index and made IndexSVG component
  components/IndexSVG.jsx
  pages/index.js
Labels: Landing, Ready for Review

#205 Attempt At Upload+Shadow Again
  components/Listing.jsx
  components/Upload.jsx
Labels: Ready for Review, Map

#206 Public and Private Drops
  components/List.jsx
  components/Listing.jsx
  components/Overlay.jsx
  components/Song.jsx
  components/View.jsx
  components/holder.jsx
  pages/api/getPrivateDrops.js
  pages/api/getSong.js
  pages/map.js
Labels: Dashboard, Ready for Review, Backend, Map

#216 Mgolwalla/editbio
  components/ProfileInformation.jsx
  pages/api/updateBio.js
  pages/profile.js
Labels: Ready for Review, Backend, Google

#217 added search icon
  components/Upload.jsx
Labels: Dashboard, Ready for Review

#219 Add Env Vars
  cloudbuild.yaml
Labels: Ready for Review, Bugfix, Backend

#220 No More Resizing
  components/Upload.jsx
Labels: Dashboard, Ready for Review

#222 Add Hover on Upload
  components/Upload.jsx
Labels: Dashboard, Ready for Review, Bugfix

#221 Get Current Coordinates
  components/Upload.jsx
Labels: Dashboard, Ready for Review

#223 Convert Current Location to City Name
  components/Upload.jsx
  components/View.jsx
Labels: Dashboard, Ready for Review, Backend

#226 Mgolwalla/profilesvg
  components/Listing.jsx
  components/Song.jsx
  pages/profile.js
Labels: Ready for Review, Profile, Spotify

#227 Fix View & Upload Toggle Behaviors
  components/Listing.jsx
  components/Song.jsx
Labels: Ready for Review, Map

#228 Lb rodrigo/profile data
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  pages/api/getProfileDrops.js
  pages/profile.js
Labels: Ready for Review, Profile

#230 click album -> redir to spotify
  components/Listing.jsx
  components/Song.jsx
  components/View.jsx
  pages/api/getSong.js
Labels: Ready for Review, Backend, Spotify

#232 Grabbed Description and Search input data
  components/Upload.jsx
Labels: Ready for Review, Backend, Map

#237 formating and city into profile page
  components/Profiledrop.jsx
Labels: Profile, Google

#235 Fixed Reverse Geoncoding Call in View.jsx
  components/View.jsx
Labels: Ready for Review, Bugfix, Map

#234 fits height of page
  pages/profile.js
Labels: Bugfix

#238 Add Static Maps
  components/Profiledrop.jsx
Labels: Ready for Review, Profile, Google

#240 Add Temp Marker
  components/Profiledrop.jsx
Labels: Ready for Review, Profile

#243 Upload Drop Package
  components/Listing.jsx
  components/Upload.jsx
  pages/api/searchSpotify.js
Labels: Dashboard, Ready for Review, Spotify

#241 Add Hashtags
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  pages/profile.js
Labels: Ready for Review, Profile

#246 Display Markers and Click Functionality
  components/Gmap.jsx
  components/Listing.jsx
  components/Overlay.jsx
  pages/api/getSong.js
  pages/map.js
Labels: Ready for Review, Spotify, Google, Map

#247 listing component, clean width
  components/Listing.jsx
  components/Overlay.jsx
  components/Song.jsx
  components/Upload.jsx
  components/View.jsx
  pages/map.js
  tailwind.config.js
Labels: Ready for Review, Map

#249 Pulled Song Information from Spotify
  components/Profiledrop.jsx
Labels: Ready for Review, Profile, Backend

#251 image always there when rendering
  components/ProfileImage.jsx
  pages/profile.js
Labels: Ready for Review, Bugfix

#257 FINISH BEATDROP
  components/Upload.jsx
  pages/api/uploadDrop.js
Labels: Dashboard, Ready for Review, Backend

#265 dropped icon chnaged in profile page
  components/ProfileInformation.jsx
  public/beatdrop-logo_black.png
Labels: Ready for Review, Profile

#266 Lb rodrigo/upload padding
  components/Upload.jsx
Labels: Ready for Review, Map

#267 Profile DropDown fix
  components/Profiledrop.jsx
Labels: Ready for Review, Profile

#268 Lb rodrigo/fix nan
  components/Song.jsx
  pages/api/uploadDrop.js
Labels: Bugfix, Google, Map

#274 Lb rodrigo/timestamp profile
  components/Profiledrop.jsx
Labels: Profile, Bugfix

#275 Lb rodrigo/time stamp view
  components/View.jsx
Labels: Bugfix, Map

#277 Lb rodrigo/artist
  components/Profiledrop.jsx
Labels: Profile, Bugfix

#281 Update View.jsx
  components/View.jsx
Labels: Dashboard

#283 Error Messages
  components/Gmap.jsx
  components/Upload.jsx
  pages/api/uploadDrop.js
Labels: Dashboard

#286 Changes
  components/Gmap.jsx
  components/Listing.jsx
  components/ProfileInformation.jsx
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  components/Song.jsx
  components/Upload.jsx
  components/View.jsx
  components/useAudio.jsx
  pages/api/getProfileDrops.js
  pages/api/getSong.js
Labels: Dashboard, Backend, Spotify, Google, Map

#288 Changes
  components/Gmap.jsx
  components/Profiledrop.jsx
  components/Upload.jsx
  components/View.jsx
Labels: Dashboard, Ready for Review, Bugfix

#287 profile drop takes full width
  components/Profiledrop.jsx
Labels: Ready for Review, Profile

#291 Mgolwalla/listingalign
  components/Listing.jsx
  components/Profiledrop.jsx
  components/Song.jsx
Labels: Bugfix, Map

#290 star yellow
  components/Profiledrop.jsx
Labels: Profile, Bugfix

#289 Updated Description Text in About Page
  components/Welcome.jsx
  components/WhatIsBeatdrop.jsx
  cypress/e2e/welcome.cy.js
Labels: Ready for Review, About

#295 Set a Limit on Profile Bio
  components/ProfileInformation.jsx
Labels: Ready for Review, Profile

#297 added a 280 character limit to the upload description
  components/Upload.jsx
Labels: Bugfix, Map

#299 added margins for view and upload
  components/Upload.jsx
  components/View.jsx
Labels: Dashboard

#302 Update Description
  components/Profiledrop.jsx
  pages/api/updateDropDescription.js
Labels: Dashboard, Ready for Review, Backend, Map

#305 Private drops scrollbar
  components/Listing.jsx
  wq
Labels: Dashboard, UI/UX

#308 Changes
  components/Gmap.jsx
  components/Listing.jsx
  components/Overlay.jsx
  pages/map.js
Labels: Dashboard, Bugfix, Backend, Spotify, Google

#310 Add New Users
  pages/api/getUserInfo.js
  wq
Labels: Dashboard, Ready for Review, Backend, Google

#309 Mgolwalla/editcaptionstyling
  components/Profiledrop.jsx
Labels: Profile, UI/UX

#311 OPTIMIZEEEEEE
  components/Gmap.jsx
  components/Listing.jsx
  components/Overlay.jsx
  components/Profiledrop.jsx
  components/Profiledrops.jsx
  components/Song.jsx
  components/View.jsx
  pages/api/getPrivateDrops.js
  pages/api/getPublicDrops.js
  pages/api/getSong.js
  pages/map.js
  pages/profile.js
Labels: Dashboard, Ready for Review, Profile, Bugfix, Backend, Spotify, Google, Map

#314 name -> username on view and listing
  components/Listing.jsx
  components/View.jsx
Labels: Dashboard, Bugfix

#315 no more 1 days ago
  components/Profiledrop.jsx
Labels: Profile, Bugfix

#317 dropbox white background
  components/Profiledrop.jsx
Labels: Profile

#318 Unit Testing
  cypress/component/Listing.cy.jsx
  cypress/component/ProfileImage.cy.jsx
  cypress/component/ProfileInformation.cy.jsx
  cypress/component/Song.cy.jsx
  cypress/component/Upload.cy.jsx
  cypress/component/View.cy.jsx
  cypress/e2e/profile.cy.js
Labels: Testing

#319 indexsvg component test
  cypress/component/IndexSVG.cy.jsx
Labels: Testing
