Repository shahdivyank/beatdrop, pull requests merged in 2024-08, with the labels that each got.

#377 Navigation + Profile Page
  app/(dashboard)/_layout.tsx
  app/(dashboard)/create.tsx
  app/(dashboard)/index.tsx
  app/(dashboard)/profile.tsx
  app/_layout.tsx
  app/index.tsx
  app/onboarding/_layout.tsx
  components/home/index.tsx
  components/profile/drops.tsx
  components/profile/header.tsx
  components/profile/index.tsx
  components/profile/navigation.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Ready for Review

#379 Create Beatdrop Foundation
  app/(dashboard)/_layout.tsx
  app/(dashboard)/create.tsx
  app/(dashboard)/dashboard.tsx
  app/(dashboard)/index.tsx
  app/_layout.tsx
  components/create/details.tsx
  components/create/index.tsx
  components/create/search.tsx
  components/dashboard/index.tsx
  components/global/beat.tsx
  components/global/tag.tsx
  components/home/index.tsx
  components/profile/drops.tsx
  package-lock.json
  package.json
  tailwind.config.js
  types/beat.ts
Labels: Ready for Review

#388 Onboarding
  app/onboarding/[stage].tsx
  app/onboarding/_layout.tsx
  components/dashboard/index.tsx
  components/home/index.tsx
  components/onboarding/index.tsx
Labels: Ready for Review

#390 Dashboard
  .eslintrc.js
  babel.config.js
  components/create/details.tsx
  components/create/index.tsx
  components/create/search.tsx
  components/dashboard/index.tsx
  components/dashboard/search.tsx
  components/dashboard/toolbar.tsx
  components/global/beat.tsx
  components/profile/drops.tsx
  package-lock.json
  package.json
  tailwind.config.js
  types/beat.ts
Labels: Dashboard, Ready for Review

#394 Turned icons to svg
  assets/icons/ArrowDown.svg
  assets/icons/Caption.svg
  assets/icons/Cross.svg
  assets/icons/Friends.svg
  assets/icons/Map_Pin.svg
  assets/icons/Plus.svg
  assets/icons/Tags.svg
  components/create/details.tsx
Labels: Bugfix

#397 Remove Section Header
  app/_layout.tsx
  components/create/details.tsx
  components/dashboard/index.tsx
  components/home/index.tsx
Labels: Ready for Review, Bugfix, Onboarding

#396 made text area bigger
  components/create/details.tsx
Labels: Ready for Review

#399 Current location
  components/create/details.tsx
Labels: Ready for Review, Create

#405 finished landing
  assets/images/homeBG.png
  components/create/index.tsx
  components/home/index.tsx
Labels: Landing, Ready for Review

#410 Configured Eslint and Prettier, added Husky Pre-commit and Pre-push Hooks
  .eslintrc.cjs
  .husky/pre-push
  components/create/details.tsx
  components/create/search.tsx
  package-lock.json
  package.json
Labels: Repository

#408 Update Global Font Style
  app/_layout.tsx
  assets/fonts/Outfit-Regular.ttf
  assets/fonts/SpaceMono-Regular.ttf
  package-lock.json
  package.json
Labels: Profile, Bugfix

#409 removed current like and comment icons and imported SVG icons
  assets/icons/Comment.svg
  assets/icons/Like.svg
  components/dashboard/index.tsx
Labels: Dashboard, Ready for Review, Bugfix

#412 added padding
  components/create/details.tsx
  components/create/search.tsx
Labels: Ready for Review, Bugfix

#413 Github Actions
  .github/workflows/pull-request.yaml
  app/_layout.tsx
  package.json
  utils/formatSeonds.ts
Labels: Repository, Ready for Review

#421 Remove Onboarding Header
  app/_layout.tsx
Labels: Ready for Review, Bugfix, Onboarding

#420 added to gitignore
  .gitignore
Labels: Ready for Review

#422 toast inn the works
  app/_layout.tsx
  components/dashboard/index.tsx
  package-lock.json
  package.json
  tailwind.config.js
  utils/toast/config.tsx
  utils/toast/index.ts
Labels: Ready for Review

#425 Implement Add Comment
  assets/icons/Send.svg
  components/dashboard/comment.tsx
  components/dashboard/index.tsx
Labels: Ready for Review

#426 add drizzle + examples
  .gitignore
  db/index.ts
  db/queries/delete.ts
  db/queries/insert.ts
  db/queries/select.ts
  db/queries/update.ts
  db/schema.ts
  drizzle.config.ts
  migrations/0000_fast_proudstar.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/_journal.json
  package-lock.json
  package.json
Labels: Ready for Review, Backend

#428 Audio Hook
  components/global/beat.tsx
  hooks/useAudio.tsx
  package-lock.json
  package.json
Labels: Ready for Review

#427 Auto Reverse-Geocoding
  components/create/details.tsx
Labels: Ready for Review, Bugfix

#429 Add Icon Family
  app/(dashboard)/_layout.tsx
  app/_layout.tsx
  assets/icons/ArrowDown.svg
  assets/icons/Caption.svg
  assets/icons/Comment.svg
  assets/icons/Cross.svg
  assets/icons/Friends.svg
  assets/icons/Like.svg
  assets/icons/Map_Pin.svg
  assets/icons/Plus.svg
  assets/icons/Search.svg
  assets/icons/Send.svg
  assets/icons/Tags.svg
  assets/icons/coolicons.ttf
  assets/icons/selection.json
  components/Icon.tsx
  components/create/details.tsx
  components/create/search.tsx
  components/dashboard/comment.tsx
  components/dashboard/index.tsx
  components/dashboard/search.tsx
  components/global/beat.tsx
  components/profile/header.tsx
  utils/formatSeconds.ts
Labels: Bugfix
