Repository shahdivyank/beatdrop, pull requests merged in 2024-09, with the labels that each got.

#440 Add Map Functionality
  assets/__mock__/pin.png
  components/create/index.tsx
  components/dashboard/index.tsx
  types/index.ts
Labels: Ready for Review, Map

#447 added bg to search bar
  components/create/search.tsx
  tailwind.config.js
Labels: Ready for Review, Create

#443 State Management Setup
  components/create/details.tsx
  components/create/index.tsx
  components/dashboard/comment.tsx
  components/dashboard/index.tsx
  components/profile/drops.tsx
  components/profile/header.tsx
  db/__mock__/comments.tsx
  db/__mock__/drops.tsx
  hooks/useDrops.tsx
  hooks/useUser.tsx
  package-lock.json
  package.json
  types/index.ts
Labels: Dashboard, Ready for Review, Profile, Create

#446 added api wrapper
  hooks/useFetch.ts
Labels: Repository, Ready for Review

#450 Visiblity Dropdown
  components/create/details.tsx
Labels: Ready for Review

#448 Beat Stick Top
  components/dashboard/index.tsx
  components/global/beat.tsx
Labels: Ready for Review

#452 Persist Comments
  components/dashboard/comment.tsx
  components/dashboard/index.tsx
  hooks/useDrops.ts
  hooks/useDrops.tsx
  hooks/useUser.ts
Labels: Dashboard, State Management

#454 Fix Profile Drops
  app/_layout.tsx
  assets/fonts/Outfit-Medium.ttf
  components/global/beat.tsx
Labels: Profile, Bugfix

#455 Profile + Cancel Modal
  components/create/cancel.tsx
  components/create/details.tsx
  components/profile/drops.tsx
  components/profile/header.tsx
  components/profile/index.tsx
  components/profile/navigation.tsx
  hooks/useUser.ts
  tailwind.config.js
Labels: Dashboard, Profile

#453 Added Prettierrc File with Prettier tailwind, ran npm run start
  .prettierrc
  components/create/cancel.tsx
  components/create/details.tsx
  components/create/index.tsx
  components/create/search.tsx
  components/dashboard/comment.tsx
  components/dashboard/index.tsx
  components/dashboard/search.tsx
  components/dashboard/toolbar.tsx
  components/global/beat.tsx
  components/home/index.tsx
  components/onboarding/index.tsx
  components/profile/header.tsx
  components/profile/navigation.tsx
  package-lock.json
  package.json
Labels: Repository

#456 Approximate location
  components/create/details.tsx
  utils/georandomizer.tsx
Labels: Backend

#458 Beat Drop Expansion
  components/dashboard/index.tsx
  db/__mock__/drops.tsx
Labels: Ready for Review

#459 Spotify Search
  components/create/details.tsx
  components/create/index.tsx
  components/create/search.tsx
  components/dashboard/index.tsx
  components/global/beat.tsx
  hooks/useAudio.tsx
  hooks/useFetch.ts
  types/index.ts
  utils/services/Fetch.ts
  utils/services/Spotify.ts
Labels: Spotify, Create

#461 Youtube Search
  components/create/search.tsx
  components/global/beat.tsx
  hooks/useAudio.tsx
  utils/services/Spotify.ts
  utils/services/YouTube.ts
Labels: Create, YouTube

#464 changed icon to match figma
  components/dashboard/index.tsx
Labels: Ready for Review, Bugfix

#457 Profile Beat Expansion
  app/[drop].tsx
  components/dashboard/index.tsx
  components/drop.tsx
  components/global/beat.tsx
  components/profile/drops.tsx
  db/__mock__/drops.tsx
Labels: Ready for Review, Profile

#470 Resolve Drop Comments Scroll Bug
  components/drop.tsx
Labels: Dashboard, Bugfix

#472 Fardinzam/truncate
  components/create/search.tsx
  components/drop.tsx
  components/global/beat.tsx
Labels: Ready for Review, Bugfix, YouTube

#471 Profile Validation
  components/profile/edit/header.tsx
  components/profile/edit/layout.tsx
  components/profile/edit/name.tsx
  components/profile/edit/username.tsx
  package-lock.json
  package.json
  schemas/users.ts
  utils/profile.ts
Labels: Ready for Review
